# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Vim4u
tagline:          A place where we learn Vim (the Editior) :)
url:              http://vim4u.com/
paginate:         10
baseurl:          /
author:
  name:           Rituraj Ratan
  url:            https://twitter.com/ratanrituraj
  email:          riturajratan@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/riturajratan.github.io
